In [12]:
import numpy as np
def sigmoid( x):
        return 1/(1 + np.exp(-x))
def sigmoid_derivative( x):
    return sigmoid(x)*(1-sigmoid(x))
def initialize_weights(input_size, hidden_size, output_size):
      np.random.seed(42)
      weights_input_hidden = np.random.rand(input_size, hidden_size)
      weights_hidden_output = np.random.rand(hidden_size, output_size)
      return weights_input_hidden, weights_hidden_output
def calculate_loss(predictions, targets):
      return np.mean((targets-predictions)**2)
def forward_pass(inputs, weights_input_hidden, weights_hidden_output):
      hidden_layer_input = np.dot(inputs, weights_input_hidden)
      hidden_layer_output = sigmoid(hidden_layer_input)

      output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
      output_layer_output = sigmoid(output_layer_input)

      return hidden_layer_output, output_layer_output
def backward_prop(inputs, targets, weights_input_hidden, weights_hidden_output, learning_rate, hidden_layer_output, output_layer_output):
      output_error = targets - output_layer_output
      output_delta = output_error*(sigmoid_derivative(output_layer_output))

      hidden_error = output_delta.dot(weights_hidden_output.T)
      hidden_delta = hidden_error*(sigmoid_derivative(hidden_layer_output))

      weights_hidden_output += hidden_layer_output.T.dot(output_delta)*learning_rate
      weights_input_hidden += inputs.T.dot(sigmoid_derivative(hidden_delta))*learning_rate

def train_nn(inputs, target, hidden_size, output_size, learning_rate, epochs):
    weights_input_hidden, weights_hidden_output = initialize_weights(inputs.shape[1], hidden_size, output_size)
    for epoch in range(epochs):
        hidden_layer_output, output_layer_output = forward_pass(inputs, weights_input_hidden, weights_hidden_output)
        backward_prop(inputs, target, weights_input_hidden, weights_hidden_output, learning_rate, hidden_layer_output, output_layer_output)
        loss = calculate_loss(output_layer_output, target)
        if(epoch % 1000 == 0):
              print(f"Epoch: {epoch}, Loss: {loss}")
    
    return weights_input_hidden, weights_hidden_output

In [13]:
inputs = np.array([[0, 0], [0, 1], [1, 0], [1,1]])
targets = np.array([[0], [1], [1], [1]])

hidden_size = 4
output_size = 1
learning_rate = 0.01
epochs = 10000

trained_weights_input_hidden, trained_weights_hidden_output = train_nn(inputs, targets, hidden_size, output_size, learning_rate, epochs)

Epoch: 0, Loss: 0.1680709485899095
Epoch: 1000, Loss: 0.14366427945165577
Epoch: 2000, Loss: 0.14304914095911775
Epoch: 3000, Loss: 0.1430275908043642
Epoch: 4000, Loss: 0.14302677423651097
Epoch: 5000, Loss: 0.14302674287121278
Epoch: 6000, Loss: 0.14302674166366433
Epoch: 7000, Loss: 0.14302674161715587
Epoch: 8000, Loss: 0.1430267416153644
Epoch: 9000, Loss: 0.14302674161529547


In [15]:
print(trained_weights_input_hidden,"\n", trained_weights_hidden_output)

[[50.37445516 50.95058297 50.73199196 50.59838592]
 [50.15593298 50.15586182 50.05808163 50.86590241]] 
 [[ 0.49382384]
 [ 0.61711644]
 [-0.07952112]
 [ 0.8912086 ]]
